# Generated by Django 4.2.4 on 2023-09-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
